### ISSUE TITLE
24-06-14(금) 스크럼

### ISSUE THREAD

**Issue by taehwan01** [nhnacademy-be6-5ritang/book-store-front-gateway#2]
### - TODO
> - 아키텍처 그림
> - SONARQUBE 키 생성
> - 프로젝트 세팅
> - GitHub Actions CD 환경 구축
> - 일정 조율
> - 깃사용법 주의사항
> - 프로젝트 구조
> - 코딩컨벤션

### - 10시 스크럼
- [ ] 아키텍처 설계 -> 아래꺼 끝나고 백엔드 설계?
- [x] SONARQUBE 키 생성
- 프로젝트 세팅
- - [x] 포트 포워딩 8080 -> 80
- - [x] 스프링 프로젝트 생성 -> [FRONT] Controller ("/") API, 디렉토리 구조
- - [ ] FRONT 템플릿 결정
- - [ ] 스프링 프로젝트 생성 -> [BACK] API, 데이터베이스 연결, 디렉토리 구조 등
- [ ] CD 환경 구축
- [ ] 로드맵 날짜 지정
